export function Contact(){
    const content = document.querySelector('#content');
    content.innerHTML='';
    const title = document.createElement('h1');
    title.className = 'contact-title';
    title.innerHTML='Big Burger - Contact Info';
    const firstRow = document.createElement('div');
    firstRow.className = 'contact-section';
    const placeColumn = document.createElement('div');
    placeColumn.className = 'contact-column';
    const place = document.createElement('h3');
    place.innerHTML='Location:';
    const res = document.createElement('p');
    res.innerHTML='Big Burger HQ <br> <br> Bole Atlas, Addis Ababa, Ethiopia <br> <br> Open daily: 10:00 AM - 11:00 PM';
    placeColumn.appendChild(place);
    placeColumn.appendChild(res);
    const deliveryColumn = document.createElement('div');
    deliveryColumn.className = 'contact-column';
    const del = document.createElement('h3');
    del.innerHTML='Delivery and Reservations:';
    const phone = document.createElement('p');
    phone.innerHTML='• Phone: +251 91 234 5678 <br> WhatsApp: +251 91 876 5432<br> Email: order@bigburger.et';
    deliveryColumn.appendChild(del);
    deliveryColumn.appendChild(phone);
    firstRow.appendChild(placeColumn);
    firstRow.appendChild(deliveryColumn);
    const secondRow = document.createElement('div');
    secondRow.className = 'contact-section';
    const socialColumn = document.createElement('div');
    socialColumn.className = 'contact-column';
    const med = document.createElement('h3');
    med.innerHTML='Social Media:';
    const info = document.createElement('p');
    info.innerHTML='Instagram: @bigburger.et<br> TikTok: @bigburger_addis<br> YouTube: Big Burger Ethiopia <br> Facebook: facebook.com/bigburger.et <br> Twitter/X: @BigBurgerET';
    socialColumn.appendChild(med);
    socialColumn.appendChild(info); 
    const partnersColumn = document.createElement('div');
    partnersColumn.className = 'contact-column';
    const part = document.createElement('h3');
    part.innerHTML='Delivery partners:';
    const list = document.createElement('p');
    list.innerHTML='Yegna Delivery <br> ZMall Express<br> HelloCourier';
    partnersColumn.appendChild(part);
    partnersColumn.appendChild(list);
    secondRow.appendChild(socialColumn);
    secondRow.appendChild(partnersColumn);
    content.appendChild(title);
    content.appendChild(firstRow);
    content.appendChild(secondRow);
}