export function Menu(){
    const content = document.querySelector('#content');
    content.innerHTML='';
    const h1 = document.createElement('h1');
    h1.textContent= 'Our Menu:';
    content.appendChild(h1);
    const doubleContainer = document.createElement('div');
    doubleContainer.className='items';
    const double = document.createElement('img');
    double.src='https://cdn.pixabay.com/photo/2018/03/04/20/08/burger-3199088_1280.jpg';
    double.alt ='double burger';
    double.width= 200;
    const doublePrice = document.createElement('p');
    doublePrice.className='price';
    doublePrice.textContent = 'Double Burger - 399.99 Birr';
    doubleContainer.appendChild(double);
    doubleContainer.appendChild(doublePrice);
    content.appendChild(doubleContainer);
    const cheeseContainer = document.createElement('div');
    cheeseContainer.className= 'items';
    const cheese = document.createElement('img');
    cheese.src='https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940';
    cheese.alt ='cheese burger';
    cheese.width= 200;
    const cheesePrice = document.createElement('p');
    cheesePrice.className='price';
    cheesePrice.textContent = 'Cheese Burger - 349.99 Birr';
    cheeseContainer.appendChild(cheese);
    cheeseContainer.appendChild(cheesePrice);
    content.appendChild(cheeseContainer);
    const beefContainer = document.createElement('div');
    beefContainer.className='items';
    const beef = document.createElement('img');
    beef.src='https://images.pexels.com/photos/1556688/pexels-photo-1556688.jpeg';
    beef.alt='beef burger';
    beef.width=200;
    const beefPrice = document.createElement('p');
    beefPrice.className='price';
    beefPrice.textContent = 'Beef Burger - 299.99 Birr';
    beefContainer.appendChild(beef);
    beefContainer.appendChild(beefPrice);
    content.appendChild(beefContainer);
    const specialContainer = document.createElement('div');
    specialContainer.className='items';
    const special = document.createElement('img');
    special.src='https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=800&q=80';
    special.alt='special burger';
    special.width=200;
    const specialPrice = document.createElement('p');
    specialPrice.className='price';
    specialPrice.textContent = 'Special Burger - 499.99 Birr';
    specialContainer.appendChild(special);
    specialContainer.appendChild(specialPrice);
    content.appendChild(specialContainer);
    const cokeContainer = document.createElement('div');
    cokeContainer.className='items';
    const coke = document.createElement('img');
    coke.src='https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500';
    coke.alt='coke';
    coke.width=170;
    const cokePrice = document.createElement('p');
    cokePrice.className='price';
    cokePrice.textContent = 'Coke - 59.99 Birr';
    cokeContainer.appendChild(coke);
    cokeContainer.appendChild(cokePrice);
    content.appendChild(cokeContainer);
}